version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "buildSrc/src/main/java/Dependencies.kt" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "buildSrc/src/main/java/Dependencies.kt" }}
      - run:
          name: Build
          command: ./gradlew autodispose:jacocoTestReport
      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash)
